version: 1
services:
  - type: web
    name: my-flask-app      
    env: python             
    plan: free              
    buildCommand: pip install -r requirements.txt
    startCommand: python3 api/index.py
    autoDeploy: true
    routes:
      - src: /api/(.*)
        dest: /api/index.py
